// -----------------------------------------------------------------------------
// Data returned by Google
// -----------------------------------------------------------------------------

type UserProfile = {
    email?: string;
    [key: string]: unknown;
};

type TokenResponse = {
    access_token: string;
    token_type: string;
    expires_in?: number;
};

// -----------------------------------------------------------------------------
// OAuth configuration
// -----------------------------------------------------------------------------

// The browser serves the site on port 5500. The backend on port 3000 keeps the
// Google client secret private and performs the authorization-code exchange.
const AUTH_SERVER_ORIGIN = 'http://localhost:3000';
const CLIENT_ID = "423278388631-b9tk58lpag1ioq47uou0capsnvj898ii.apps.googleusercontent.com";
const AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth";
const USERINFO_ENDPOINT = "https://openidconnect.googleapis.com/v1/userinfo";

// -----------------------------------------------------------------------------
// Page elements and shared UI helpers
// -----------------------------------------------------------------------------

const registerPage = document.getElementById('registerPage') as HTMLElement;
const loginPage = document.getElementById('loginPage') as HTMLElement;
const profilePage = document.getElementById('profilePage') as HTMLElement;
const errorPage = document.getElementById('errorPage') as HTMLElement;
const redirectUri = `${window.location.origin}/auth.html`;

// Updates text only when the requested element exists, keeping error handling
// from causing a second failure if the page markup changes.
const setText = (id: string, value: string): void => {
    const element = document.getElementById(id);
    if (element) {
        element.textContent = value;
    }
};

// Displays exactly one top-level page section at a time.
const showPage = (page: HTMLElement): void => {
    [registerPage, loginPage, profilePage, errorPage].forEach((section) => {
        section.hidden = section !== page;
    });
};

// Switches between the register and login choices while always hiding the
// profile and error sections during unauthenticated navigation.
const showAuthenticationPages = (page: HTMLElement): void => {
    registerPage.hidden = page !== registerPage;
    loginPage.hidden = page !== loginPage;
    profilePage.hidden = true;
    errorPage.hidden = true;
};

// -----------------------------------------------------------------------------
// PKCE helpers
// -----------------------------------------------------------------------------

// Google expects the verifier and challenge in URL-safe base64 without
// padding. This conversion works directly with browser-generated bytes.
const toBase64Url = (bytes: Uint8Array): string => {
    let binary = '';
    bytes.forEach((byte) => {
        binary += String.fromCharCode(byte);
    });
    return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
};

// Creates a cryptographically random value used as either OAuth state or the
// PKCE verifier. The verifier is never sent to Google in the authorization URL.
const createCodeVerifier = (): string => {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    return toBase64Url(bytes);
};

// Derives the PKCE S256 challenge from the verifier stored in sessionStorage.
const createCodeChallenge = async (verifier: string): Promise<string> => {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier));
    return toBase64Url(new Uint8Array(digest));
};

// -----------------------------------------------------------------------------
// Authorization start
// -----------------------------------------------------------------------------

const startAuthorization = async (isRegistration: boolean): Promise<void> => {
    // State protects against forged callbacks. The separate verifier proves
    // that this browser started the authorization request.
    const state = createCodeVerifier();
    const codeVerifier = createCodeVerifier();
    const codeChallenge = await createCodeChallenge(codeVerifier);
    sessionStorage.setItem('oauth_state', state);
    sessionStorage.setItem('oauth_code_verifier', codeVerifier);

    const authorizationUrl = new URL(AUTHORIZATION_ENDPOINT);
    authorizationUrl.search = new URLSearchParams({
        response_type: 'code',
        client_id: CLIENT_ID,
        redirect_uri: redirectUri,
        scope: 'openid profile email',
        state,
        code_challenge: codeChallenge,
        code_challenge_method: 'S256',
        ...(isRegistration ? { prompt: 'select_account' } : {}),
    }).toString();
    // Leaving the page sends the user to Google. Google later redirects back
    // to auth.html with a short-lived authorization code.
    window.location.assign(authorizationUrl.href);
};

// -----------------------------------------------------------------------------
// Backend token exchange and profile request
// -----------------------------------------------------------------------------

const exchangeCodeForToken = async (code: string): Promise<TokenResponse> => {
    const codeVerifier = sessionStorage.getItem('oauth_code_verifier');
    if (!codeVerifier) {
        throw new Error('Missing PKCE code verifier. Start login again.');
    }
    // The authorization code is exchanged by our backend so the client secret
    // never reaches browser JavaScript.
    const response = await fetch(`${AUTH_SERVER_ORIGIN}/api/token`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            code,
            code_verifier: codeVerifier,
            redirect_uri: redirectUri,
        }),
    });
    if (!response.ok) {
        const errorBody = await response.text();
        console.error('Token exchange error body:', errorBody);
        throw new Error(`Token exchange failed (${response.status}).`);
    }
    return response.json() as Promise<TokenResponse>;
};

// Uses the access token returned by Google to load the signed-in user's basic
// profile data for any page that needs it.
const getUserProfile = async (accessToken: string): Promise<UserProfile> => {
    const response = await fetch(USERINFO_ENDPOINT, {
        headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!response.ok) {
        throw new Error(`User profile request failed (${response.status}).`);
    }
    return response.json() as Promise<UserProfile>;
};

// -----------------------------------------------------------------------------
// Authentication page startup
// -----------------------------------------------------------------------------

(async (): Promise<void> => {
    try {
        const params = new URLSearchParams(window.location.search);
        const error = params.get('error');
        const code = params.get('code');

        // Google can return an error instead of a code, for example when the
        // user cancels the consent screen.
        if (error) {
            setText('authError', `Authentication failed: ${params.get('error_description') ?? error}`);
            showPage(errorPage);
            return;
        }
        if (code) {
            // Validate state before accepting the code. A mismatch means this
            // callback was not created by the current browser session.
            const returnedState = params.get('state');
            const savedState = sessionStorage.getItem('oauth_state');
            if (!returnedState || returnedState !== savedState) {
                throw new Error('Invalid OAuth state. Start login again.');
            }
            const token = await exchangeCodeForToken(code);
            sessionStorage.setItem('oauth_access_token', token.access_token);
            sessionStorage.removeItem('oauth_state');
            sessionStorage.removeItem('oauth_code_verifier');
            // Authentication is complete, so the auth page should not remain
            // visible after the token has been stored.
            window.location.assign('/index.html');
        }
        const accessToken = sessionStorage.getItem('oauth_access_token');
        if (accessToken) {
            // This handles a user who revisits auth.html after already signing
            // in during the current browser session.
            window.location.assign('/index.html');
            return;
        }

        // No callback or existing token means the visitor needs to choose an
        // authentication action.
        showAuthenticationPages(registerPage);
        document.getElementById('registerButton')?.addEventListener('click', () => void startAuthorization(true));
        document.getElementById('loginButton')?.addEventListener('click', () => void startAuthorization(false));
        document.getElementById('showLoginButton')?.addEventListener('click', () => showAuthenticationPages(loginPage));
        document.getElementById('showRegisterButton')?.addEventListener('click', () => showAuthenticationPages(registerPage));
    } catch (error) {
        // Any OAuth, network, or validation failure is shown in the dedicated
        // error section instead of leaving the page in a partially initialized
        // state.
        setText('authError', error instanceof Error ? error.message : 'Authentication failed.');
        showPage(errorPage);
    }
})();